<a href="https://colab.research.google.com/github/farzanashaheenit-data/PyTorch/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch Fundamentals

In [8]:
import torch
import numpy
from matplotlib import pyplot as plt
import pandas as pd

In [4]:
print(torch.__version__)

2.10.0+cpu


In [7]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


Creating Tensors

In [13]:
##scalar
scalar=torch.tensor(7)
print(scalar)
print(scalar.ndim)
##get tensor back as python int

print(scalar.item())

tensor(7)
0
7


In [14]:
##vector
vector=torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [15]:
##matrix

matrix=torch.tensor([[7,8],[9,10]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)

tensor([[ 7,  8],
        [ 9, 10]])
torch.Size([2, 2])
2


In [24]:
matrix2=torch.tensor([[1,1,1,3],[1,1,2,3]])
matrix3=torch.tensor([[1],[1]])
print(matrix2)
print(matrix2.shape)
#print(matrix2.ndim)
print(matrix3.shape)

tensor([[1, 1, 1, 3],
        [1, 1, 2, 3]])
torch.Size([2, 4])
torch.Size([2, 1])


In [51]:
TENSOR=torch.tensor([[[1,2,2,4],[4,5,6,6],[7,8,9,6],[1,2,2,4],[4,5,6,6],[7,8,9,6]]])
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])


3
torch.Size([1, 6, 4])
tensor([[1, 2, 2, 4],
        [4, 5, 6, 6],
        [7, 8, 9, 6],
        [1, 2, 2, 4],
        [4, 5, 6, 6],
        [7, 8, 9, 6]])


Random Tensors

In [54]:
TENSOR=torch.rand(3,4)
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[0.8229, 0.6709, 0.3627, 0.2328],
        [0.0605, 0.6344, 0.7484, 0.8587],
        [0.9707, 0.3539, 0.1346, 0.2644]])
2
torch.Size([3, 4])


In [55]:
random_image_size_tensor=torch.rand(size=(224,224,3)) ## height,width ,image channels
random_image_size_tensor

tensor([[[0.6792, 0.9831, 0.1336],
         [0.8981, 0.6601, 0.0451],
         [0.8216, 0.3403, 0.3168],
         ...,
         [0.4611, 0.7890, 0.9904],
         [0.4773, 0.9129, 0.5607],
         [0.5827, 0.2102, 0.9065]],

        [[0.8566, 0.7116, 0.5424],
         [0.7859, 0.8940, 0.0400],
         [0.0977, 0.2046, 0.6402],
         ...,
         [0.2597, 0.9914, 0.1890],
         [0.1624, 0.7853, 0.7875],
         [0.1378, 0.9207, 0.5427]],

        [[0.0031, 0.4465, 0.6576],
         [0.8680, 0.5441, 0.8537],
         [0.3719, 0.0266, 0.1846],
         ...,
         [0.0751, 0.0972, 0.0548],
         [0.4796, 0.7762, 0.8075],
         [0.6948, 0.7170, 0.6707]],

        ...,

        [[0.2261, 0.8736, 0.8263],
         [0.3766, 0.3744, 0.6927],
         [0.6523, 0.4330, 0.1907],
         ...,
         [0.3551, 0.2294, 0.2899],
         [0.5397, 0.6530, 0.8929],
         [0.4096, 0.1544, 0.5480]],

        [[0.7398, 0.5895, 0.2639],
         [0.1566, 0.2615, 0.0258],
         [0.

Zeros and Ones

In [57]:
zeroes=torch.zeros(2,3)
zeroes
ones=torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Creating Range of tensors

In [64]:

print(torch.arange(2,15))
print(torch.arange(start=0,end=1000,step=100))
print(torch.arange(start=0,end=1000,step=100).ndim)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])
1


/tmp/ipykernel_44094/260163857.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(1,10))


In [68]:
##creating tensors like(create like tensors not sure about shape)

ten_zeros=torch.zeros_like(input=zeroes)
ten_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor Data Types

In [78]:
tensor_float_32=torch.tensor((1.,2.,3.),dtype=None,device=None,requires_grad=False)
#type:what type is the tensor ,device:if tensor is on cpu/gpu
#requires_grad : wether or not to track grasients with this operation
print(tensor_float_32.dtype)
tensor_float_32=torch.tensor((1.,2.,3.),dtype=torch.float16,device=None,requires_grad=False)
tensor_float_32.dtype


torch.float32


torch.float16

In [79]:
##converting float32tensor to 16
float_16_tensor=tensor_float_32.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

Finding Info about tensors


In [83]:
some_tensor=torch.rand(size=(2,2),dtype=torch.float16)
some_tensor

tensor([[0.5015, 0.9878],
        [0.9385, 0.0449]], dtype=torch.float16)

In [84]:
print(f"Tensor shape:{some_tensor.shape}")
print(f"Tensor datatype:{some_tensor.dtype}")
print(f"Tensor device:{some_tensor.device}")


Tensor shape:torch.Size([2, 2])
Tensor datatype:torch.float16
Tensor device:cpu


##Manipulating Tensors
*Addition
*Multiplication
*Subtraction
*Division
*Matrix Multiplication


In [111]:
#create tensor

tensor=torch.tensor([1.,2.,3.])
print(tensor)
print(tensor+10)
print(tensor-10)
print(tensor*10)
print(tensor/10)

tensor([1., 2., 3.])
tensor([11., 12., 13.])
tensor([-9., -8., -7.])
tensor([10., 20., 30.])
tensor([0.1000, 0.2000, 0.3000])


In [112]:
#elementwise  multiplication
tensor2=torch.ones(size=(1,3))
print(tensor ,"*",tensor2)
print(f"multiplication",{tensor * tensor2})

tensor([1., 2., 3.]) * tensor([[1., 1., 1.]])
multiplication {tensor([[1., 2., 3.]])}


##matrix multiplication



In [119]:
print(torch.matmul(tensor,tensor2.T))

tensor([6.])


In [120]:
tensor@tensor2.T

tensor([6.])

Finding mean,max,min,sum of matrices

In [128]:
matrix=torch.arange(0,11,1,dtype=torch.float32)
print(matrix)
print(torch.min(matrix))
print(torch.max(matrix))
print(torch.sum(matrix))
print(torch.mean(matrix)) ##doesnot work for long datatypes so changed the datatype tp float32

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor(0.)
tensor(10.)
tensor(55.)
tensor(5.)


In [139]:
##finding the positional min and max
print(matrix.argmin()) #find the position
print(matrix.argmax())


tensor(0)
tensor(10)


Reshaping ,Stacking ,Squeezing  and unsqueezing tensors
Reshaping :reshapes the tensor to a defined shape
stacking: combine multiple tensors sidebyside/vertical stacks/sequence of stacks
Squeezing :removes all "1" dimensions to target tensor
unsqueeze: add 1 dimension to target is tensor
permute:return a view of the input with dimesions permuted



In [146]:
#lets create a tensor

x=torch.arange(1.,10.)
print(x,x.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [145]:
x_reshaped=x.reshape(9,1)
print(x_reshaped,x.shape)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9])


In [147]:
#change the view
z=x.view(1,9)
print(z,z.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [150]:
#changing z will change x bcuz view of a tensor shares the same memory as the original input
z[:,0]=5
x,z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [159]:
##stack tensors
x_stacked=torch.stack([x,x],dim=1)
x_stacked

tensor([[5., 5.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [165]:

##torch squeeze removes single dimensions from tensor
x=torch.rand(size=(2,2))
print(x)
x_squeeze=torch.squeeze(x)
x_squeeze

tensor([[0.4873, 0.1512],
        [0.6303, 0.8317]])


tensor([[0.4873, 0.1512],
        [0.6303, 0.8317]])

In [175]:
##permute shuffles the indexs

x_original=torch.rand(size=(224,224,0))
x_original

x_permuted=x_original.permute(2,0,1)
x_permuted

tensor([], size=(0, 224, 224))

indexing

In [178]:
z=torch.rand(size=(2,2,3))
z

tensor([[[0.6883, 0.9401, 0.0020],
         [0.5800, 0.4795, 0.5967]],

        [[0.1302, 0.7757, 0.8613],
         [0.4863, 0.2480, 0.8116]]])

In [180]:
z[0],z[1]

(tensor([[0.6883, 0.9401, 0.0020],
         [0.5800, 0.4795, 0.5967]]),
 tensor([[0.1302, 0.7757, 0.8613],
         [0.4863, 0.2480, 0.8116]]))

In [181]:
z[0][0]

tensor([0.6883, 0.9401, 0.0020])

In [182]:
z[0][0][0]

tensor(0.6883)

In [195]:
z[:,1,:1]

tensor([[0.5800],
        [0.4863]])

Reproducibility

In [196]:
seed=42 ## to reproduce same tensor
torch.manual_seed(seed)

random_tensor_a=torch.rand(size=(2,2))
print(random_tensor_a)
torch.manual_seed(seed)
random_tensor_b=torch.rand(size=(2,2))
print(random_tensor_b)

print(random_tensor_a==random_tensor_b)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[True, True],
        [True, True]])


Check GPU Access

In [197]:
##setup GPU access
torch.cuda.is_available()

False

In [198]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [199]:
##count num of devices
torch.cuda.device_count()

0

In [201]:
##putting tensors on cpu/gpu
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

##move tensor on gpu if available
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])